language: cpp
compiler: gcc

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - cmake
      env:
         - MATRIX_EVAL="export CC=gcc-8 && export CXX=g++-8"

before_install:
  - eval "${MATRIX_EVAL}"
  - $CC -v && $CXX -v && cmake --version